######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 20 14:14:00 2019
######################################################################

TEMPLATE = lib
TARGET = qt_window
DEPENDPATH += .
INCLUDEPATH += .
#QMAKE_LFLAGS = -static

DESTDIR = ../lib

# Input
HEADERS += LoginDialog.h QApi.h
SOURCES += LoginDialog.cpp QApi.cpp
